/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.cloudbeaver.test.platform.util;

public class GraphQLTestConstant {

    public static final String GQL_SQL_GROUPING_RESULTSET = """
        query asyncSqlGroupingResultSet($projectId: ID, $contextId: ID!, $connectionId: ID!, $resultsId: ID!, $columnNames: [String!], $functions: [String!], $showDuplicatesOnly: Boolean, $filter: SQLDataFilter, $dataFormat: ResultDataFormat, $isInteractive: Boolean) {
          result: asyncSqlGroupingResultSet(projectId: $projectId, contextId: $contextId, connectionId: $connectionId, originalResultsId: $resultsId, columnNames: $columnNames, functions: $functions, showDuplicatesOnly: $showDuplicatesOnly, filter: $filter, dataFormat: $dataFormat, isInteractive: $isInteractive) {
            id
          }
        }
        """;

    public static final String GQL_OPEN_SESSION = """
        mutation openSession($defaultLocale: String) {
          result: openSession(defaultLocale: $defaultLocale) {
            createTime
            lastAccessTime
            cacheExpired
            locale
            actionParameters
            valid
            remainingTime
          }
        }
        """;

    public static final String GQL_ASYNC_TASK_INFO = """
        mutation asyncTaskInfo($id: String!, $removeOnFinish: Boolean!) {
          result: asyncTaskInfo(id: $id, removeOnFinish: $removeOnFinish) {
            id
            name
            running
            status
            error { message errorCode errorType }
            taskResult
          }
        }
        """;

    public static final String GQL_ASYNC_SQL_EXECUTE_RESULTS = """
        mutation asyncSqlExecuteResults($taskId: ID!) {
          result: asyncSqlExecuteResults(taskId: $taskId) {
            results {
              resultSet {
               id
               readOnly
               rowIdentifierState
               rowIdentifier {
                attributes {
                 name
                 ordinalPosition
                }
                constraintType
               }
               columns {
                 dataKind
                 entityName
                 fullTypeName
                 icon
                 description
                 label
                 maxLength
                 name
                 position
                 precision
                 required
                 autoGenerated
                 readOnly
                 readOnlyStatus
                 scale
                 typeName
                 supportedOperations {
                   id
                   expression
                   argumentCount
                 }
                }
                rowsWithMetaData {
                  data
                  metaData
                }
               }
            }
          }
        }
        """;

    public static final String GQL_SQL_RESULT_ASSOCIATIONS = """
        query sqlResultAssociations(
          $projectId: ID,
          $connectionId: ID!,
          $contextId: ID!,
          $resultsId: ID!,
          $isReference: Boolean!
        ) {
          result: sqlResultAssociations(
            projectId: $projectId,
            connectionId: $connectionId,
            contextId: $contextId,
            resultsId: $resultsId,
            isReference: $isReference
          ) {
            reference
            associationName
            targetCatalogName
            targetSchemaName
            targetEntityName
            targetNodePath
            columnMapping {
              sourceColumnIndex
              sourceColumnName
              targetColumnName
            }
          }
        }
        """;

    public static final String GQL_ASYNC_SQL_EXECUTE = """
        mutation asyncSqlExecuteQuery($projectId: ID, $connectionId: ID!, $contextId: ID!, $sql: String!) {
          result: asyncSqlExecuteQuery(projectId: $projectId, connectionId: $connectionId, contextId: $contextId, sql: $sql) {
            id
          }
        }
        """;

    public static final String GQL_SQL_CONTEXT_CREATE = """
        mutation sqlContextCreate($projectId: ID, $connectionId: ID!) {
          result: sqlContextCreate(projectId: $projectId, connectionId: $connectionId) {
            id
            projectId
            connectionId
          }
        }
        """;

    public static final String GQL_ASYNC_SQL_EXPLAIN_EXECUTION_PLAN = """
        mutation asyncSqlExplainExecutionPlan(
          $projectId: ID!,
          $connectionId: ID!,
          $contextId: ID!,
          $query: String!,
          $configuration: Object!
        ) {
          result: asyncSqlExplainExecutionPlan(
            projectId: $projectId,
            connectionId: $connectionId,
            contextId: $contextId,
            query: $query,
            configuration: $configuration
          ) {
            id
            running
            status
            error {
              message
              errorCode
              errorType
            }
          }
        }
        """;

    public static final String GQL_ASYNC_SQL_EXPLAIN_EXECUTION_PLAN_RESULT = """
        mutation asyncSqlExplainExecutionPlanResult($taskId: ID!) {
          result: asyncSqlExplainExecutionPlanResult(taskId: $taskId) {
            query
            hasCost
            hasRows
            hasDuration
            durationMeasure
            nodes {
              id
              parentId
              kind
              name
              type
              condition
              description
              cost
              rowCount
              duration
              percent
            }
          }
        }
        """;

    public static final String GQL_ASYNC_READ_DATA_FROM_CONTAINER = """
        mutation asyncReadDataFromContainer(
            $projectId: ID,
            $connectionId: ID!,
            $contextId: ID!,
            $containerNodePath: ID!,
            $resultId: ID,
            $filter: SQLDataFilter
        ) {
            result: asyncReadDataFromContainer(
                projectId: $projectId,
                connectionId: $connectionId,
                contextId: $contextId,
                containerNodePath: $containerNodePath,
                resultId: $resultId,
                filter: $filter
            ) {
                id
            }
        }
        """;

    public static final String GQL_CREATE_USER = """
        query createUser($userId: ID!, $enabled: Boolean!, $authRole: String) {
          result: createUser(userId: $userId, enabled: $enabled, authRole: $authRole) { userId }
        }""";

    public static final String GQL_DELETE_USER = """
        query deleteUser($userId: ID!) {
          result: deleteUser(userId: $userId)
        }""";

    public static final String GQL_SET_USER_CREDENTIALS = """
        query setUserCredentials($userId: ID!, $providerId: ID!, $credentials: Object!) {
          result: setUserCredentials(userId: $userId, providerId: $providerId, credentials: $credentials)
        }""";

    public static final String GQL_ADMIN_USER_INFO = """
        query adminUserInfo($userId: ID!) {
          result: adminUserInfo(userId: $userId) {
            userId
            enabled
            authRole
            metaParameters
            configurationParameters
            grantedTeams
            linkedAuthProviders
            grantedConnections {
              connectionId
              dataSourceId
              subjectId
              subjectType
            }
            origins {
              type
              subType
              displayName
              icon
              configuration
              details {
                id
                displayName
                description
                category
                dataType
                value
                defaultValue
              }
            }
            disableDate
            disabledBy
            disableReason
            lastLoginTime
          }
        }""";

    public static final String GQL_CREATE_CONNECTION = """
        mutation createConnection($config: ConnectionConfig!, $projectId: ID) {
          result: createConnection(config: $config, projectId: $projectId) { id }
        }""";

    public static final String GQL_UPDATE_CONNECTION = """
        mutation updateConnection($projectId: ID!, $config: ConnectionConfig!) {
          result: updateConnection(projectId: $projectId, config: $config) { id defaultUserPreferences }
        }""";

    public static final String GQL_GET_CONN_SETTINGS = """
        query getUserConnectionsAuthProperties(
          $projectId: ID
          $connectionId: ID
          $projectIds: [ID!]
        ) {
          result: userConnections(
            projectId: $projectId
            id: $connectionId
            projectIds: $projectIds
          ) {
            id,
            name,
            defaultUserPreferences
          }
        }""";

    public static final String GQL_DELETE_CONNECTION = """
        mutation deleteConnection($id: ID!, $projectId: ID) {
          result: deleteConnection(id: $id, projectId: $projectId)
        }""";

    public static final String GQL_ADD_CONN_ACCESS = """
        query addConnectionsAccess($projectId: ID!, $connectionIds: [ID!]!, $subjects: [ID!]!) {
          result: addConnectionsAccess(projectId: $projectId, connectionIds: $connectionIds, subjects: $subjects)
        }""";

    public static final String GQL_SET_OBJECT_SETTINGS = """
        mutation SetObjectSettingsForDatasource($id: ID!, $projectId: ID, $settings: Object!) {
          result: setObjectSettingsForDatasource(id: $id, projectId: $projectId, settings: $settings)
        }""";

    public static final String GQL_USER_CONNECTIONS = """
        query userConnections {
          result: userConnections {
            id
            name
            driverId
            projectId
          }
        }""";
}
