/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.cloudbeaver.service.sql;

import org.jkiss.code.NotNull;
import org.jkiss.dbeaver.DBException;
import org.jkiss.dbeaver.Log;
import org.jkiss.dbeaver.model.DBPDataKind;
import org.jkiss.dbeaver.model.DBPEvaluationContext;
import org.jkiss.dbeaver.model.DBValueFormatting;
import org.jkiss.dbeaver.model.data.DBDAttributeBinding;
import org.jkiss.dbeaver.model.exec.DBCLogicalOperator;
import org.jkiss.dbeaver.model.exec.DBExecUtils;
import org.jkiss.dbeaver.model.meta.Property;
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
import org.jkiss.dbeaver.model.runtime.VoidProgressMonitor;
import org.jkiss.dbeaver.model.struct.*;
import org.jkiss.dbeaver.model.virtual.DBVUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * Web SQL query resultset.
 */
public class WebSQLQueryResultColumn {

    private static final Log log = Log.getLog(WebSQLQueryResultColumn.class);

    private final DBDAttributeBinding attrMeta;

    public WebSQLQueryResultColumn(DBDAttributeBinding attrMeta) {
        this.attrMeta = attrMeta;
    }

    DBDAttributeBinding getAttribute() {
        return attrMeta;
    }

    @Property
    public Integer getPosition() {
        return attrMeta.getOrdinalPosition();
    }

    @Property
    public String getName() {
        return WebSQLUtils.getColumnName(attrMeta);
    }

    @Property
    public String getLabel() {
        if (attrMeta.getParentObject() != null && attrMeta.getParentObject().getDataKind() != DBPDataKind.DOCUMENT) {
            return attrMeta.getParentObject().getFullyQualifiedName(DBPEvaluationContext.UI) + "." + attrMeta.getLabel();
        }
        return attrMeta.getLabel();
    }

    @Property
    public String getIcon() {
        return DBValueFormatting.getObjectImage(attrMeta).getLocation();
    }

    @Property
    public String getEntityName() {
        return attrMeta.getMetaAttribute().getEntityName();
    }

    @Property
    public String getDataKind() {
        return attrMeta.getDataKind().name();
    }

    @Property
    public String getTypeName() {
        return attrMeta.getTypeName();
    }

    @Property
    public String getFullTypeName() {
        return attrMeta.getFullTypeName();
    }

    @Property
    public long getMaxLength() {
        return attrMeta.getMaxLength();
    }

    @Property
    public Integer getScale() {
        return attrMeta.getScale();
    }

    @Property
    public Integer getPrecision() {
        return attrMeta.getPrecision();
    }

    @Property
    public boolean isRequired() {
        return attrMeta.isRequired();
    }

    @Property
    public boolean isAutoGenerated() {
        return attrMeta.isAutoGenerated();
    }

    @Property
    public String getDescription() {
        return attrMeta.getDescription();
    }

    @Property
    public boolean isReadOnly() {
        return DBExecUtils.isAttributeReadOnly(attrMeta, true);
    }

    @Property
    public String getReadOnlyStatus() {
        return DBExecUtils.getAttributeReadOnlyStatus(attrMeta);
    }

    @Property
    public DBCLogicalOperator[] getSupportedOperations() {
        return attrMeta.getValueHandler().getSupportedOperators(attrMeta);
    }

    @Property
    public List<WebSQLQueryResultColumnReference> getReferences() {
        List<WebSQLQueryResultColumnReference> references = new ArrayList<>();

        // Forward references: foreign keys where this column is the source
        List<DBSEntityReferrer> referrers = attrMeta.getReferrers();
        if (referrers != null) {
            for (DBSEntityReferrer referrer : referrers) {
                if (referrer instanceof DBSEntityAssociation association) {
                    references.add(new WebSQLQueryResultColumnReference(association, false));
                }
            }
        }

        // Reverse references: foreign keys from other entities targeting this column
        DBSEntityAttribute entityAttribute = attrMeta.getEntityAttribute();
        if (entityAttribute != null) {
            DBSEntity parentEntity = entityAttribute.getParentObject();
            if (parentEntity != null) {
                DBRProgressMonitor monitor = new VoidProgressMonitor();
                for (DBSEntityAssociation reverseRef : DBVUtils.getAllReferences(monitor, parentEntity)) {
                    try {
                        if (referenceTargetsAttribute(monitor, reverseRef, entityAttribute)) {
                            references.add(new WebSQLQueryResultColumnReference(reverseRef, true));
                        }
                    } catch (DBException e) {
                        log.debug("Error reading attributes for reverse reference " + reverseRef.getName(), e);
                    }
                }
            }
        }

        return references;
    }

    private static boolean referenceTargetsAttribute(
        @NotNull DBRProgressMonitor monitor,
        @NotNull DBSEntityAssociation association,
        @NotNull DBSEntityAttribute attribute
    ) throws DBException {
        DBSEntityConstraint refConstraint = association.getReferencedConstraint();
        if (!(refConstraint instanceof DBSEntityReferrer referrer)) {
            return false;
        }
        List<? extends DBSEntityAttributeRef> attrs = referrer.getAttributeReferences(monitor);
        if (attrs == null) {
            return false;
        }
        for (DBSEntityAttributeRef ref : attrs) {
            if (attribute.equals(ref.getAttribute())) {
                return true;
            }
        }
        return false;
    }

    @Override
    public String toString() {
        return attrMeta.getName();
    }
}
