/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.cloudbeaver.service.sql.resultset;

import org.jkiss.code.NotNull;
import org.jkiss.dbeaver.model.DBUtils;
import org.jkiss.dbeaver.model.data.DBDAttributeBinding;
import org.jkiss.dbeaver.model.data.DBDDataReceiver;
import org.jkiss.dbeaver.model.data.DBDValueHandler;
import org.jkiss.dbeaver.model.exec.*;
import org.jkiss.utils.CommonUtils;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Key data receiver
 */
public class KeyDataReceiver implements DBDDataReceiver {

    private final DBDAttributeBinding[] attributes;
    private final Object[] rowValues;
    private final Set<Integer> updatedAttributes = new HashSet<>();

    public KeyDataReceiver(@NotNull DBDAttributeBinding[] attributes, @NotNull Object[] row) {
        this.attributes = attributes;
        this.rowValues = row;
    }

    @Override
    public void fetchStart(@NotNull DBCSession session, @NotNull DBCResultSet resultSet, long offset, long maxRows) {
        // No action required
    }

    @Override
    public void fetchRow(@NotNull DBCSession session, @NotNull DBCResultSet resultSet)
    throws DBCException {

        DBCResultSetMetaData rsMeta = resultSet.getMeta();
        List<? extends DBCAttributeMetaData> keyAttributes = rsMeta.getAttributes();
        for (int i = 0; i < keyAttributes.size(); i++) {
            DBCAttributeMetaData keyAttribute = keyAttributes.get(i);
            DBDValueHandler valueHandler = DBUtils.findValueHandler(session, keyAttribute);
            Object keyValue = valueHandler.fetchValueObject(session, resultSet, keyAttribute, i);
            if (keyValue == null) {
                continue;
            }
            if (!CommonUtils.isEmpty(keyAttribute.getName())) {
                DBDAttributeBinding binding = DBUtils.findObject(attributes, keyAttribute.getName());
                if (binding != null) {
                    int index = getAttributePosition(binding);
                    rowValues[index] = keyValue;
                    updatedAttributes.add(index);
                    continue;
                }
            }
            // Key not found
            // Try to find and update auto-increment column
            for (int k = 0; k < attributes.length; k++) {
                DBDAttributeBinding column = attributes[k];
                if (column.isAutoGenerated() && updatedAttributes.add(k)) {
                    rowValues[k] = keyValue;
                    break;
                }
            }
        }
    }

    @Override
    public void fetchEnd(@NotNull DBCSession session, @NotNull DBCResultSet resultSet) {
        // No action required
    }

    @Override
    public void close() {
        // No action required
    }

    private int getAttributePosition(@NotNull DBDAttributeBinding attribute) throws DBCException {
        for (int i = 0; i < attributes.length; i++) {
            if (attributes[i] == attribute) {
                return i;
            }
        }
        throw new DBCException("Generated key attribute '" + attribute.getName() + "' is not present in the row");
    }
}
