/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.cloudbeaver.service.sql.resultset;

import org.jkiss.code.NotNull;
import org.jkiss.dbeaver.model.DBUtils;
import org.jkiss.dbeaver.model.data.DBDAttributeBinding;
import org.jkiss.dbeaver.model.data.DBDDataReceiver;
import org.jkiss.dbeaver.model.data.DBDValueHandler;
import org.jkiss.dbeaver.model.exec.*;
import org.jkiss.utils.CommonUtils;

import java.util.List;

/**
 * Key data receiver
 */
public class KeyDataReceiver implements DBDDataReceiver {

    private final List<DBDAttributeBinding> attributes;
    private Object[] row;

    public KeyDataReceiver(@NotNull List<DBDAttributeBinding> results) {
        this.attributes = results;
    }

    void setRow(Object[] row) {
        this.row = row;
    }

    @Override
    public void fetchStart(@NotNull DBCSession session, @NotNull DBCResultSet resultSet, long offset, long maxRows) {

    }

    @Override
    public void fetchRow(@NotNull DBCSession session, @NotNull DBCResultSet resultSet)
    throws DBCException {

        DBCResultSetMetaData rsMeta = resultSet.getMeta();
        List<? extends DBCAttributeMetaData> keyAttributes = rsMeta.getAttributes();
        for (int i = 0; i < keyAttributes.size(); i++) {
            DBCAttributeMetaData keyAttribute = keyAttributes.get(i);
            DBDValueHandler valueHandler = DBUtils.findValueHandler(session, keyAttribute);
            Object keyValue = valueHandler.fetchValueObject(session, resultSet, keyAttribute, i);
            if (keyValue == null) {
                continue;
            }
            if (!CommonUtils.isEmpty(keyAttribute.getName())) {
                DBDAttributeBinding binding = DBUtils.findObject(attributes, keyAttribute.getName());
                if (binding != null) {
                    // Got it. Just update column oldValue
                    row[binding.getOrdinalPosition()] = keyValue;
                    continue;
                }
            }
            // Key not found
            // Try to find and update auto-increment column
            for (int k = 0; k < attributes.size(); k++) {
                DBDAttributeBinding column = attributes.get(k);
                if (column.isAutoGenerated()) {
                    // Got it
                    row[k] = keyValue;
                    break;
                }
            }
        }
    }

    @Override
    public void fetchEnd(@NotNull DBCSession session, @NotNull DBCResultSet resultSet) {

    }

    @Override
    public void close() {
    }
}
