FROM eclipse-temurin:25-jdk-noble AS launcher

COPY cloudbeaver /opt/cloudbeaver
COPY scripts/CloudBeaverLauncher.java /opt/cloudbeaver/CloudBeaverLauncher.java
WORKDIR /opt/cloudbeaver
RUN javac --release 25 CloudBeaverLauncher.java && \
    rm CloudBeaverLauncher.java && \
    mkdir -p workspace/GlobalConfiguration/.dbeaver && \
    cp conf/initial-data-sources.conf workspace/GlobalConfiguration/.dbeaver/data-sources.json

FROM gcr.io/distroless/java25-debian13:nonroot

LABEL org.opencontainers.image.authors="DBeaver Corp, devops@dbeaver.com"

COPY --from=launcher --chown=nonroot:nonroot /opt/cloudbeaver /opt/cloudbeaver

EXPOSE 8978
WORKDIR /opt/cloudbeaver

ENTRYPOINT ["/usr/bin/java", "-cp", "/opt/cloudbeaver", "CloudBeaverLauncher"]
