model_web_ai_query_confirmation_title = Confirm query execution
model_web_ai_query_confirmation_message = The query you're about to execute can modify existing data or schema.\nDo you want to continue?

model_web_dialog_sql_param_title = Bind parameter(s)

