model_web_ai_query_confirmation_title = Confirm query execution
model_web_ai_query_confirmation_message = The query you're about to execute can modify existing data or schema.\nDo you want to continue?
model_web_dangerous_update_confirmation_title = Confirm dangerous query execution
model_web_dangerous_update_confirmation_message = You are about to execute {0} statement without a WHERE clause.\nData loss is possible. Are you sure?
model_web_drop_query_confirmation_title = Confirm dangerous query execution
model_web_drop_query_confirmation_message = You are about to execute a DROP statement.\nData loss is possible. Are you sure?