/*
 * CloudBeaver - Cloud Database Manager
 * Copyright (C) 2020-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0.
 * you may not use this file except in compliance with the License.
 */

import { observer } from 'mobx-react-lite';

import { Alert, Text, useTranslate } from '@cloudbeaver/core-blocks';
import { AiMessageType, type AiMessage } from '@cloudbeaver/core-sdk';

import { AIChatUserMessage } from './AIChatUserMessage.js';
import { AIChatAssistentFormatter } from '../AIChatAssistentFormatter/AIChatAssistentFormatter.js';
import { AIChatAutogeneratedUserMessage } from './AIChatAutogeneratedUserMessage.js';
import { MarkdownFormatter } from '../MarkdownFormatter.js';
import { AIChatFunctionFormatter } from '../AIChatFunctionFormatter/AIChatFunctionFormatter.js';
import { AIChatFunctionConfirmationFormatter } from '../AIChatFunctionFormatter/AIChatFunctionConfirmationFormatter.js';
import { isFunctionConfirmationMessage, isFunctionMessage } from '../AIChatMessagesResource.js';

interface Props {
  message: AiMessage;
}

export const AIChatMessageFormatter = observer<Props>(function AIChatMessageFormatter({ message }) {
  const translate = useTranslate();

  if (message.role === AiMessageType.User) {
    const autoGenerated = message.content !== message.displayMessage;

    if (autoGenerated) {
      return <AIChatAutogeneratedUserMessage message={message} />;
    }

    return (
      <AIChatUserMessage message={message}>
        <p>{message.displayMessage}</p>
      </AIChatUserMessage>
    );
  }

  if (message.role === AiMessageType.Assistant) {
    return <AIChatAssistentFormatter message={message} />;
  }

  if (message.role === AiMessageType.System) {
    return <div>{message.content}</div>;
  }

  if (message.role === AiMessageType.Error) {
    return (
      <Alert variant="error" className="tw:break-all tw:my-2">
        <Text>{message.content}</Text>
      </Alert>
    );
  }

  if (message.role === AiMessageType.Warning) {
    return (
      <Alert className="tw:break-all tw:my-2">
        <MarkdownFormatter content={message.content} conversationId={message.conversationId} />
      </Alert>
    );
  }

  if (isFunctionConfirmationMessage(message)) {
    return <AIChatFunctionConfirmationFormatter message={message} />;
  }

  if (isFunctionMessage(message)) {
    return <AIChatFunctionFormatter message={message} />;
  }

  return (
    <Alert title={translate('ui_error')}>
      <Text>{translate('plugin_ai_chat_message_format_not_supported')}</Text>
    </Alert>
  );
});
