/*
 * CloudBeaver - Cloud Database Manager
 * Copyright (C) 2020-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0.
 * you may not use this file except in compliance with the License.
 */

import { observer } from 'mobx-react-lite';

import { useTranslate } from '@cloudbeaver/core-blocks';
import type { AiMessage } from '@cloudbeaver/core-sdk';

import { AIChatUserMessage } from './AIChatUserMessage.js';
import { MarkdownFormatter } from '../MarkdownFormatter.js';
import classes from './AIChatAutogeneratedUserMessage.module.css';

interface Props {
  message: AiMessage;
}

export const AIChatAutogeneratedUserMessage = observer<Props>(function AIChatAutogeneratedUserMessage({ message }) {
  const translate = useTranslate();

  return (
    <AIChatUserMessage message={message}>
      <div
        title={translate('plugin_ai_chat_user_message_auto_generated_hint')}
        className="tw:text-(--theme-on-surface) tw:bg-[var(--theme-secondary)] tw:w-max tw:px-[6px] tw:py-[2px] tw:rounded-sm tw:text-xs tw:font-medium"
      >
        {translate('plugin_ai_chat_user_message_auto_generated')}
      </div>
      <div className={classes['markdown']}>
        <MarkdownFormatter content={message.displayMessage} conversationId={message.conversationId} />
      </div>
    </AIChatUserMessage>
  );
});
