ALTER TABLE {table_prefix}CB_SCHEMA_INFO
ADD MODULE_ID VARCHAR(10);

UPDATE {table_prefix}CB_SCHEMA_INFO
SET MODULE_ID = 'CB_CE';

ALTER TABLE {table_prefix}CB_SCHEMA_INFO
ALTER COLUMN MODULE_ID SET NOT NULL;

