CREATE TABLE {table_prefix}CB_ACCESS_TOKEN
(
    TOKEN_ID        VARCHAR(128) NOT NULL,
    USER_ID         VARCHAR(128) NOT NULL,
    TOKEN_NAME      VARCHAR(128) NOT NULL,
    CREATE_TIME     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EXPIRATION_TIME TIMESTAMP NULL,

    PRIMARY KEY (USER_ID, TOKEN_ID),
    UNIQUE (USER_ID, TOKEN_NAME),
    FOREIGN KEY (USER_ID) REFERENCES {table_prefix}CB_USER(USER_ID) ON DELETE CASCADE
);