CREATE TABLE {table_prefix}CB_USER_PARAMETERS(
    USER_ID VARCHAR(128) NOT NULL,
    PARAM_ID VARCHAR(32) NOT NULL,
    PARAM_VALUE VARCHAR(1024),

    PRIMARY KEY(USER_ID,PARAM_ID),
    FOREIGN KEY(USER_ID) REFERENCES {table_prefix}CB_USER(USER_ID) ON DELETE CASCADE
);
