CREATE TABLE {table_prefix}CB_GLOBAL_PERMISSIONS_DEFAULTS
(
    PERMISSION_ID         VARCHAR(64)  NOT NULL,
    ENABED_BY_DEFAULT     CHAR(1)      NOT NULL,
    GRANTED_BY            VARCHAR(128) NOT NULL,
    GRANT_TIME            TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,

    PRIMARY KEY (PERMISSION_ID)
);

CREATE TABLE {table_prefix}CB_GLOBAL_PERMISSIONS
(
    SUBJECT_ID    VARCHAR(128) NOT NULL,
    PERMISSION_ID VARCHAR(64)  NOT NULL,
    IS_ENABLED    CHAR(1)      NOT NULL,
    GRANTED_BY    VARCHAR(128) NOT NULL,
    GRANT_TIME    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,

    PRIMARY KEY (SUBJECT_ID, PERMISSION_ID),
    FOREIGN KEY (SUBJECT_ID) REFERENCES {table_prefix}CB_AUTH_SUBJECT (SUBJECT_ID) ON DELETE CASCADE
);