DROP TABLE {table_prefix}CB_OBJECT_SETTINGS;

CREATE TABLE {table_prefix}CB_OBJECT_SETTINGS
(
    PROJECT_ID  VARCHAR(128) NOT NULL,
    OBJECT_ID   VARCHAR(128) NOT NULL,
    OBJECT_TYPE VARCHAR(128) NOT NULL,
    SUBJECT_ID  VARCHAR(128) NOT NULL,
    SETTING_ID  VARCHAR(255)  NOT NULL,
    SETTING_VALUE TEXT,

    UPDATE_TIME  TIMESTAMP    NOT NULL,
    UPDATED_BY  VARCHAR(128) NOT NULL,

    PRIMARY KEY (PROJECT_ID, SUBJECT_ID, OBJECT_TYPE, OBJECT_ID, SETTING_ID),
    FOREIGN KEY (SUBJECT_ID) REFERENCES {table_prefix}CB_AUTH_SUBJECT(SUBJECT_ID) ON DELETE CASCADE
);
