ALTER TABLE {table_prefix}CB_OBJECT_SETTINGS ADD PROJECT_ID VARCHAR(128);
ALTER TABLE {table_prefix}CB_OBJECT_SETTINGS ALTER COLUMN SETTING_ID TYPE VARCHAR(128);
CREATE INDEX CB_OBJECT_SETTINGS_IDX ON {table_prefix}CB_OBJECT_SETTINGS(SUBJECT_ID,PROJECT_ID, OBJECT_TYPE, OBJECT_ID, SETTING_ID);