CREATE TABLE {table_prefix}CB_USER_SECRETS
(
    USER_ID                        VARCHAR(128) NOT NULL,
    SECRET_ID                      VARCHAR(512) NOT NULL,
    SECRET_VALUE                   VARCHAR(65000) NOT NULL,

    SECRET_LABEL                   VARCHAR(128),
    SECRET_DESCRIPTION             VARCHAR(1024),

    UPDATE_TIME                    TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,

    PRIMARY KEY (USER_ID, SECRET_ID),
    FOREIGN KEY (USER_ID) REFERENCES {table_prefix}CB_USER (USER_ID) ON DELETE CASCADE
);

CREATE INDEX CB_USER_SECRETS_ID ON {table_prefix}CB_USER_SECRETS (USER_ID,SECRET_ID);
