ALTER TABLE {table_prefix}CB_USER ADD CHANGE_DATE TIMESTAMP NULL;
ALTER TABLE {table_prefix}CB_USER ADD DISABLE_BY_USER_ID VARCHAR(32) NULL;
ALTER TABLE {table_prefix}CB_USER ADD DISABLE_REASON VARCHAR(128) NULL;
