CREATE TABLE {table_prefix}CB_DATABASE_CONNECTION
(
    CONNECTION_ID                  VARCHAR(128) NOT NULL,
    CONNECTION_TIME                TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONNECTION_STATUS              VARCHAR(32) NOT NULL,
    USER_ID                        VARCHAR(128) NOT NULL,

    FOREIGN KEY (USER_ID) REFERENCES {table_prefix}CB_USER (USER_ID) ON DELETE CASCADE
);