ALTER TABLE {table_prefix}CB_USER ADD CHANGE_DATE TIMESTAMP NULL;
ALTER TABLE {table_prefix}CB_USER ADD DISABLED_BY VARCHAR(128) NULL;
ALTER TABLE {table_prefix}CB_USER ADD DISABLE_REASON VARCHAR(128) NULL;
