CREATE TABLE CB_OBJECT_PERMISSIONS
(
    OBJECT_ID   VARCHAR(128) NOT NULL,
    OBJECT_TYPE VARCHAR(128) NOT NULL,
    SUBJECT_ID  VARCHAR(128) NOT NULL,

    PERMISSION  VARCHAR(32)  NOT NULL,

    GRANT_TIME  TIMESTAMP    NOT NULL,
    GRANTED_BY  VARCHAR(128) NOT NULL,

    PRIMARY KEY (SUBJECT_ID, OBJECT_TYPE, OBJECT_ID, PERMISSION),
    FOREIGN KEY (SUBJECT_ID) REFERENCES CB_AUTH_SUBJECT (SUBJECT_ID) ON DELETE CASCADE
);

INSERT INTO CB_OBJECT_PERMISSIONS (OBJECT_ID, OBJECT_TYPE, SUBJECT_ID, PERMISSION, GRANTED_BY, GRANT_TIME)
SELECT DA.DATASOURCE_ID, 'datasource', DA.SUBJECT_ID, 'access', DA.GRANTED_BY, DA.GRANT_TIME
FROM CB_DATASOURCE_ACCESS DA;

DROP TABLE CB_DATASOURCE_ACCESS;