ALTER TABLE {table_prefix}CB_AUTH_TOKEN
    ADD REFRESH_TOKEN_ID VARCHAR(128);

ALTER TABLE {table_prefix}CB_AUTH_TOKEN
    ADD REFRESH_TOKEN_EXPIRATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;