DROP TABLE {table_prefix}CB_OBJECT_SETTINGS;

CREATE TABLE {table_prefix}CB_OBJECT_SETTINGS(
    PROJECT_ID  VARCHAR(128),
    OBJECT_ID   VARCHAR(128) NOT NULL,
    OBJECT_TYPE VARCHAR(128) NOT NULL,
    SUBJECT_ID  VARCHAR(128) NOT NULL,
    SETTING_ID  VARCHAR(128)  NOT NULL,
    SETTING_VALUE VARCHAR(1024),

    UPDATE_TIME  TIMESTAMP    NOT NULL,
    UPDATED_BY  VARCHAR(128) NOT NULL,

    PRIMARY KEY (SUBJECT_ID, OBJECT_TYPE, OBJECT_ID, SETTING_ID),
    FOREIGN KEY (SUBJECT_ID) REFERENCES {table_prefix}CB_AUTH_SUBJECT(SUBJECT_ID) ON DELETE CASCADE
);
CREATE INDEX CB_OBJECT_SETTINGS_IDX ON {table_prefix}CB_OBJECT_SETTINGS(SUBJECT_ID,PROJECT_ID, OBJECT_TYPE, OBJECT_ID, SETTING_ID);