ALTER TABLE CB_AUTH_TOKEN ADD COLUMN AUTH_ROLE VARCHAR(32);

ALTER TABLE CB_USER ADD COLUMN DEFAULT_AUTH_ROLE VARCHAR(32) NULL;

CREATE TABLE CB_EXTERNAL_TEAM
(
    TEAM_ID          VARCHAR(128) NOT NULL,
    EXTERNAL_TEAM_ID VARCHAR(128) NOT NULL,

    PRIMARY KEY (TEAM_ID,EXTERNAL_TEAM_ID),
    FOREIGN KEY (TEAM_ID) REFERENCES CB_ROLE (ROLE_ID) ON DELETE CASCADE
);
