DROP TABLE {table_prefix}CB_EXTERNAL_TEAM;
DROP TABLE {table_prefix}CB_SESSION_STATE;
DROP TABLE {table_prefix}CB_SESSION_LOG;
DROP TABLE {table_prefix}CB_INSTANCE_EVENT;
DROP TABLE {table_prefix}CB_WORKSPACE;
DROP TABLE {table_prefix}CB_AUTH_CONFIGURATION;
DROP TABLE {table_prefix}CB_AUTH_PROVIDER;
