nodeLinker: pnp

packageExtensions:
  '@material/touch-target@*':
    dependencies:
      '@material/base': '*'
  '@material/switch@*':
    dependencies:
      '@material/density': '*'
  'vite-multiple-assets@*':
    dependencies:
      'mime-types': '*'
