name: Backend Build

on:
  # Allows you to reuse workflows by referencing their YAML files
  workflow_call:

jobs:
  build-backend:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: cloudbeaver

      - name: Clone Deps Repositories
        uses: dbeaver/github-actions/clone-repositories@devel
        with:
          project_deps_path: './cloudbeaver/project.deps'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6

      - name: Run build script
        run: ./build-backend.sh
        shell: bash
        working-directory: ./cloudbeaver/deploy

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-build-artifacts
          path: cloudbeaver/deploy/cloudbeaver
          if-no-files-found: error
