name: Backend Build

on:
  # push:
  #   branches:
  #     - devel
  # pull_request:
  #   branches:
  #     - devel
  #   paths-ignore:
  #     - "webapp/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows you to reuse workflows by referencing their YAML files
  workflow_call:

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run build script
        run: sudo ./build-backend.sh
        shell: bash
        working-directory: ./deploy

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-build-artifacts
          path: deploy/cloudbeaver
