name: Common

on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      skip_cache:
        description: "Skip cache restoration"
        required: false
        default: "false"

jobs:
  call-backend-build:
    name: Build
    uses: ./.github/workflows/backend-build.yml

  call-frontend-build:
    name: Build
    uses: ./.github/workflows/frontend-build.yml
    with:
      skip_cache: ${{ github.event.inputs.skip_cache }}

  call-frontend-tests:
    name: Run
    needs: [call-frontend-build]
    uses: ./.github/workflows/frontend-tests.yml

  call-docker-build-and-push:
    name: Run
    needs: [call-backend-build, call-frontend-build]
    uses: ./.github/workflows/docker-build-and-push.yml
