name: Build and Push Docker Image

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows you to reuse workflows by referencing their YAML files
  workflow_call:

jobs:
  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download backend artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-build-artifacts
          path: deploy/cloudbeaver/

      - name: Download frontend artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-build-artifacts
          path: deploy/cloudbeaver/web

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run custom Docker build script
        run: ./make-docker-container.sh
        shell: bash
        working-directory: ./deploy/docker

      - name: Tag Docker Image
        run: |
          IMAGE_NAME=dbeaver/cloudbeaver
          BRANCH_NAME=${{ github.head_ref || github.ref_name }}
          TAG_NAME=$(echo $BRANCH_NAME | sed 's/[^a-zA-Z0-9._-]/-/g')
          docker tag $IMAGE_NAME:dev $IMAGE_NAME:$TAG_NAME
