name: Frontend Lint

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows you to reuse workflows by referencing their YAML files
  workflow_call:

jobs:
  lint:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
          cache-dependency-path: webapp/yarn.lock

      - name: restore node_modules
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('webapp/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: yarn install --frozen-lockfile
        uses: borales/actions-yarn@v5
        with:
          dir: webapp
          cmd: install

      - name: Lint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          filter_mode: file
          workdir: webapp
          fail_on_error: true
          eslint_flags: "--ext .ts,.tsx"
